name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Umami
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            UMAMI_ID="faa54201-a249-4ddc-9732-88c6ac7fdf5f"
          else
            # Non production deployment
            UMAMI_ID="127a9e7a-1fe0-404f-bb17-915882ebd403"
          fi
          # The data-website-id in the source code is now just a placeholder
          # and will be replaced during the build process.
          sed -i "s/data-website-id=\"[a-f0-9-]*\"/data-website-id=\"$UMAMI_ID\"/" public/index.html

      - name: Generate robots.txt
        # Don't allow indexing of non-production deployments.
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo -e "User-agent: *\nDisallow: /" > public/robots.txt
          fi

      - name: Fetch and Update Download Link
        run: |
          MANAGER_PROPS_URL="https://raw.githubusercontent.com/HundEdFeteTree/HappyFunTest/refs/heads/main/gradle.properties"
          VERSION=$(curl -s $MANAGER_PROPS_URL | grep -m 1 "^\s*version\s*=" | cut -d "=" -f 2 | tr -d '[:space:]')
          if [ -z "$VERSION" ]; then
            echo "Error: Could not find version string in gradle.properties." >&2
            exit 1
          fi
          DOWNLOAD_URL="https://github.com/MorpheApp/morphe-manager/releases/download/v$VERSION/morphe-manager-$VERSION.apk"
          sed -i "s|^/download.*|/download    $DOWNLOAD_URL    302|g" public/_redirects
          echo "Updated _redirects file:"
          cat public/_redirects

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: wrangler pages deploy --branch "${{ github.ref_name }}"
